@server=http://localhost:5050
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNjk5NzI5MzkzLCJleHAiOjE2OTk5MDIyMDJ9.PwDsetPvcVAV14Rew4dkDeWMzXO4l2lQwrhEVVrSfiY
### welcome to the API
GET {{server}}/

###
GET {{server}}/health

### signup
POST {{server}}/signup
Content-Type: application/json

{
    "email": "myemail2.mail.com",
    "password": "mysecretpassword"
}

### login
POST {{server}}/login
Content-Type: application/json

{
    "email": "myemail2.mail.com",
    "password": "mysecretpassword"
}


### GET ME
GET {{server}}/me
Content-Type: application/json
Authorization: Bearer {{token}}

### POSt content
POST {{server}}/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "post_content": "Mi primer post 6"
}


### GET POST BY ID
GET  {{server}}/posts/2Y2hWBdrj68UKz1YNVDsRflFUyQ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### UPDATE POST BY ID
PUT  {{server}}/posts/2Y2hWBdrj68UKz1Y HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "post_content": "Las arepas de mi tia"
}

### DELETE POST BY ID
DELETE   {{server}}/posts/2Y2hWBdrj68UKz1YNVDsRflFUyQ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET POST BY ID
GET  {{server}}/posts?page=1&pageSize=4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}